export const STUDENT_SUBMIT_ROOM = "STUDENT_SUBMIT_ROOM";
export const TEACHER_CREATE_ROOM = "TEACHER_CREATE_ROOM";
export const LOGIN_STUDENT = "LOGIN_STUDENT";
export const LOGIN_TEACHER = "LOGIN_TEACHER";
export const CHANGE_LOGIN_FORM = "CHANGE_LOGIN_FORM";
