export const LOGIN_USER = "LOGIN_USER";
export const STUDENT_JOIN_ROOM = "STUDENT_JOIN_ROOM";
export const TEACHER_CREATE_ROOM = "TEACHER_CREATE_ROOM";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
